### ISSUE TITLE
how to deal with encoding cross os

### ISSUE THREAD

**Issue by JunseiKo** [marza-animation-planet/das#11]
6fbed639253c83c87aee8a35d2eb5ec17bda11bc

An UnicodeDecodeError reported from YSBA. 
And I found it happened when model is checked in with **Japanese comment on linux**,
then check out it on windows gets this error.

The error can also be replicated in assetFinder on windows.
proj: preYSBA2025py3
env: maya2023-test
asset tokens: assets/model | car | all | render | mid | default | v020

> Traceback (most recent call last):
  File "Z:\marza/team/rnd/tools/python/picore/2.1.0/all/python\picore\publish\__init__.py", line 1822, in getLatestVersion
    vi = self.mds.get(self._versionInfoClass, **vtkns)
  File "Z:\marza\team\rnd\tools\python\pyf\1.1.0\all\python\pyf\infostore\__init__.py", line 349, in get
    path, store = self.raw_get(klass, __version__=ver, **kwargs)
  File "Z:\marza/team/rnd/tools/python/picore/2.1.0/all/python\picore\metadata\__init__.py", line 52, in raw_get
    path, store = super().raw_get(klass, __version__=__version__, **extra)
  File "Z:\marza\team\rnd\tools\python\pyf\1.1.0\all\python\pyf\infostore\__init__.py", line 296, in raw_get
    rv = das.read(path, schema_type=isc.schema, strict_schema=False)
  File "Z:\marza\team\rnd\tools\python\das\1.0.0\all\python\das\__init__.py", line 440, in read
    md, src = _read_file(path)
  File "Z:\marza\team\rnd\tools\python\das\1.0.0\all\python\das\__init__.py", line 306, in _read_file
    for l in f.readlines():
UnicodeDecodeError: 'cp932' codec can't decode byte 0x81 in position 239: illegal multibyte sequence

As the commit 6fbed639253c83c87aee8a35d2eb5ec17bda11bc , I know it can be solved by specify the encoding.
But I am not sure , if das is the right place to fix this ? Because it affects too much tools.
Do you have more infomation or ideas ?

Thank you.

**Comment by JunseiKo** [comment]
> PYTHONUTF8=1
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8

After use this , it solved problem.

Thank you. @marza-sergey  @marza-hansy
